version: "3"

services:
  frontend:
    container_name: px_bank_frontend
    build: ./frontend
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      - backend
  backend:
    build: ./backend
    container_name: px_bank_backend
    tty: true
    stdin_open: true
    command: sh
    restart: unless-stopped
    working_dir: /app-backend
    depends_on:
      - db
    volumes:
      - ./backend:/app-backend
    ports:
      - 3001:3001
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mysql:8.0.32
    container_name: px_bank_db
    restart: unless-stopped
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456

networks:
  default:
    name: px_bank_net